// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"about\" class=\"section\"><div class=\"about-content\">Software engineer passionate about building tools to simplify day-to-day workflows. I'm a big fan of self-hosting; I run various services on Docker across Raspberry Pis and a remote virtual private server. I'm also into football and the analytics side of the sport.</div><div class=\"about-social\"><a title=\"Discord\" href=\"https://discordapp.com/users/761308808823570453\" target=\"_blank\" class=\"social-link\"><img src=\"/assets/icons/discord.svg\" alt=\"Discord\"></a> <a title=\"GitHub\" href=\"https://github.com/bachtran02\" target=\"_blank\" class=\"social-link\"><img src=\"/assets/icons/github.svg\" alt=\"GitHub\"></a> <a title=\"Email\" href=\"mailto:xuanbachtran02@gmail.com\" class=\"social-link\"><img src=\"/assets/icons/email.svg\" alt=\"Email\"></a> <span class=\"social-separator\">|</span> <a href=\"/resume\" class=\"resume-link\">🔗 View my resume</a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
