// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Music() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"section\" id=\"music\"><div class=\"player\"><div id=\"music-player-content\" style=\"display: flex;\"><div class=\"player-content\"><img id=\"track-artwork\" src=\"https://i.scdn.co/image/ab67616d0000b273e319baafd16e84f0408af2a0\" alt=\"track-image\"><div class=\"music-info\"><h3 id=\"track-artist\">Mikel Arteta</h3><div class=\"track-details\"><p><a id=\"track-title\" href=\"#\" target=\"_blank\">Eighty Leon</a></p></div></div><div class=\"track-time\"><span id=\"current-time\">2:14</span> / <span id=\"total-duration\">3:45</span></div></div><div class=\"progress-bar-container\"><div id=\"progress-bar\" class=\"progress-bar\"></div></div></div><div id=\"not-streaming-message\" style=\"display: none;\"><div class=\"player-content\"><div class=\"radio-icon\"><svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"2\"></circle> <path d=\"M16.24 7.76a6 6 0 0 1 0 8.49m-8.48-.01a6 6 0 0 1 0-8.49m11.31-2.82a10 10 0 0 1 0 14.14m-14.14 0a10 10 0 0 1 0-14.14\"></path></svg></div><div class=\"music-info\"><h3>Not currently streaming!</h3></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
