// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package tmpl

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Music() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2>Listening to</h2><div class=\"player\"><div id=\"music-player-content\" style=\"display: none;\"><div class=\"info-wrapper\"><img id=\"track-artwork\" src=\"\" alt=\"track-image\"><div class=\"info\"><h3><a id=\"track-title\" href=\"#\" target=\"_blank\"></a></h3><p id=\"track-artist\"></p><div class=\"progress-and-time-wrapper\"><div class=\"time-display\"><span id=\"current-time\">00:00</span></div><div class=\"progress-bar-container\"><div id=\"progress-bar\" class=\"progress-bar\"></div></div><div class=\"time-display\"><span id=\"total-duration\">00:00</span></div></div></div></div></div><div id=\"not-streaming-message\" style=\"display: block;\">Not currently streaming!</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
